name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 60

    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2.3.4

      - name: Docker registry login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Publish
        uses: renovatebot/internal-tools@3d26ee4c6964d82e7b897a14802a00761721a555 # renovate: tag=v1.8.3
        with:
          command: "docker-builder"
          prune: true
          dry-run: ${{github.ref != 'refs/heads/main'}}
